extends: "stylelint-config-recommended"
plugins:
  stylelint-declaration-use-variable
rules:
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - function
        - if
        - for
        - each
        - include
        - extend
        - return
        - mixin
  declaration-block-no-shorthand-property-overrides: null
  no-descending-specificity: null
  sh-waqar/declaration-use-variable:
  - - "/color/"
    - "fill"
    - "stroke"
    - ignoreValues:
      - "transparent"
      - "inherit"
